### ISSUE TITLE
Crashes with CENTOS 7 EPEL repository.

### ISSUE THREAD

**Issue by awalk57** [RexOps/repositorio#15]
Works fine with centos 7 base but when configured for Epel. It crashes. Difference is that fedora Epel repository is broken up by alpha first letter. Is there a flat EPEL centos 7 repository I can use as alternative?

**Comment by krimdomu** [comment]
Hi,
thanks for the report. 

I'll try to reproduce this behaviour on a test environment.

**Comment by krimdomu** [comment]
@awalk57 
how did you configure epel for your centos 7?
Could you please post the error you get?

Thanks,
Jan

**Comment by awalk57** [comment]
ok, here was my configuration.
<Repository epel-centos-7-x86-64>
  url    = http://download.fedoraproject.org/pub/epel/7/x86_64/
  local  = epel-centos-7-x86-64/epel/7/x86_64/
  type   = Yum
</Repository>
and here is the error
[root@9708d4317fc2 rex]# repositorio --mirror --repo=epel-centos-7-x86-64
>> Going to mirror epel-centos-7-x86-64. This may take a while.

>> Downloading metadata...

100% [==============================================================================================================================================]

>> Downloading packages...

  0% [=       *                                                                                                                                     ]Error downloading http://download.fedoraproject.org/pub/epel/7/x86_64/g/ghc-stm-chans-devel-3.0.0.2-1.el7.x86_64.rpm. at /usr/local/share/perl5/Rex/Repositorio/Repository/Base.pm line 223.
        Rex::Repositorio::Repository::Base::_download_binary_file(undef, 'dest', '/var/www/html/repo/head/epel-centos-7-x86-64/epel/7/x86_64/g/...', 'url', 'http://download.fedoraproject.org/pub/epel/7/x86_64/g/ghc-stm...', 'cb', 'CODE(0xfd88828)', 'force', undef, ...) called at /usr/local/share/perl5/Rex/Repositorio/Repository/Base.pm line 130
        Rex::Repositorio::Repository::Base::download_package(undef, 'url', 'http://download.fedoraproject.org/pub/epel/7/x86_64/g/ghc-stm...', 'name', 'ghc-stm-chans-devel', 'dest', 'epel-centos-7-x86-64/epel/7/x86_64/g/ghc-stm-chans-devel-3.0....', 'cb', 'CODE(0xfd88828)', ...) called at /usr/local/share/perl5/Rex/Repositorio/Repository/Yum.pm line 165
        Rex::Repositorio::Repository::Yum::_download_packages('Rex::Repositorio::Repository::Yum=HASH(0x202fe18)', 'HASH(0x2009328)', 'HASH(0x2805fe0)', 'HASH(0x27dd710)', 'HASH(0x27dd500)', 'HASH(0x27dd350)', 'HASH(0x27dd1a0)', 'HASH(0x27dcff0)', 'HASH(0x27dce40)', ...) called at /usr/local/share/perl5/Rex/Repositorio/Repository/Yum.pm line 62
        Rex::Repositorio::Repository::Yum::mirror('Rex::Repositorio::Repository::Yum=HASH(0x202fe18)', 'update_metadata', undef, 'update_files', undef) called at /usr/local/share/perl5/Rex/Repositorio.pm line 364
        Rex::Repositorio::mirror(undef, 'repo', 'epel-centos-7-x86-64', 'update_metadata', undef, 'update_files', undef) called at /usr/local/share/perl5/Rex/Repositorio.pm line 66
        Rex::Repositorio::parse_cli_option('Rex::Repositorio=HASH(0x2009760)', 'repo', 'epel-centos-7-x86-64', 'mirror', 1) called at /usr/local/share/perl5/Rex/Repositorio.pm line 51
        Rex::Repositorio::run('Rex::Repositorio=HASH(0x2009760)', 'repo', 'epel-centos-7-x86-64', 'mirror', 1) called at /usr/local/bin/repositorio line 62

**Comment by krimdomu** [comment]
Hi @awalk57 ,

your url will redirect to a mirror. The problem here is, that sometimes it redirects to mirrors that are not existing anymore. Or it even does not redirect at all.

For example:
```
root@bac5abee7552:~# curl -I http://download.fedoraproject.org/pub/epel/7/x86_64/
HTTP/1.1 302 Found
Date: Wed, 25 Mar 2015 19:09:41 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux) mod_wsgi/3.4 Python/2.7.5
Location: http://mirror.de.leaseweb.net/epel/7/x86_64/

root@bac5abee7552:~# curl -I http://download.fedoraproject.org/pub/epel/7/x86_64/
HTTP/1.1 404 Not Found
Date: Wed, 25 Mar 2015 19:10:44 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux)
Content-Type: text/html; charset=iso-8859-1

root@bac5abee7552:~# curl -I http://download.fedoraproject.org/pub/epel/7/x86_64/
HTTP/1.1 404 Not Found
Date: Wed, 25 Mar 2015 19:10:59 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux)
Content-Type: text/html; charset=iso-8859-1

root@bac5abee7552:~# curl -I http://download.fedoraproject.org/pub/epel/7/x86_64/
HTTP/1.1 302 Found
Date: Wed, 25 Mar 2015 19:11:00 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux) mod_wsgi/3.4 Python/2.7.5
Location: http://fedora.tu-chemnitz.de/pub/linux/fedora-epel/7/x86_64/
```

So i suggest to not use download.fedoraproject.org in the url but to use a known working mirror.

HTH,
Jan

**Comment by krimdomu** [comment]
I'm closing this one because i think this is solved.
If not, feel free to open it again.

**Comment by compuguy** [comment]
I'm still seeing this issue @krimdomu even with epel 7 mirrors. Tried mirror.cogentco.com and mirror.math.princeton.edu. Both hang at package download at around 12%.
